nolibc: Add errno.h header for time.c
If we don't enable the CONFIG_HAVE_SCHED, we should get the error:
nolibc/time.c:65:3: error: errno undeclared (first use in this function)
   errno = EINVAL;
   ^~~~~
This because the uk/sched.h include the error.h implicitly. So we
add error.h to the headers.

Signed-off-by: Wei Chen <wei.chen@arm.com>
Reviewed-by: Simon Kuenzer <simon.kuenzer@neclab.eu>